version: 2.1
executors:
  build-deploy-executor:
    working_directory: ~/project
    docker:
      - image: google/cloud-sdk:latest


#名前空間にgcpをインポート
orbs:
  gcp-cli: circleci/gcp-cli@1.8.4
  browser-tools: circleci/browser-tools@0.1.4

jobs:
  build_gcpcli:
    executor: build-deploy-executor
    steps:
      - run:
          name: Initialize gcloud CLI to connect to Google Cloud
          command: |
            # Initialize gcloud CLI
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
      - run:
          name: Gcloud version check and install components.
          command: |
            #check gcloud version
            gcloud version
            #install
            apt-get install -y google-cloud-sdk-app-engine-python
            apt-get install -y python3-venv
      - checkout
      - run: mkdir test-reports
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/


  deploy_all_gcpcli:
    executor: build-deploy-executor
    steps:
      - run:
          name: Gcloud version
          command: |
            #check gcloud version
            gcloud version
      - run:
          name: deploy google app engine.
          command: |
            gcloud --quiet app deploy ./circleci/google_app_engine/app.yaml --version=test
      - run:
          name: test:check_webpage
          command: |
            export GET_URL="https://$GOOGLE_PROJECT_ID.appspot.com"
            curl -o result.html $GET_URL
            cat result_deploy_all.html

      - run:
          name: for_artifacts
          command: |
            mkdir /tmp/dumps
            cp -p result _deploy_all.html /tmp/dumps
      - store_artifacts:
          path: /tmp/dumps

  deploy_master_gcpcli:
    working_directory: ~/project
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - run:
          name: Gcloud version
          command: |
            #check gcloud version
            gcloud version
      - run:
          name: deploy google app engine.
          command: |
            gcloud --quiet app deploy ./circleci/google_app_engine/app.yaml
      - run:
          name: test:check_webpage
          command: |
            export GET_URL="https://$GOOGLE_PROJECT_ID.appspot.com"
            curl -o result.html $GET_URL
            cat result.html


      
workflows:
  version: 2.1
  install_and_check:
    jobs:
      - build_gcpcli
      - deploy_all_gcpcli:
          requires:
            - build_gcpcli
      - deploy_master_gcpcli:
          requires:
            - deploy_all_gcpcli
          filters:
            branches:
              only: master
