orbs:
  gcp-cli: circleci/gcp-cli@1.8.4
version: 2.1
workflows:
  install_and_configure_cli:
    jobs:
      - gcp-cli/install_and_initialize_cli:
          context: hashiheiContext
          executor: gcp-cli/default
jobs:
  build:
    docker:
      - image: google/cloud-sdk:latest
    working_directory: ~/circleci/google_app_engine
    steps:
      - checkout
      - gcp-cli/initialize
      - run:
        name: Deploy to Google App Engine
        command: |
          gcloud --quiet app deploy ~/circleci/google_app_engine/app.yaml