version: 2.1

#名前空間にgcpをインポート
orbs:
  gcp-cli: circleci/gcp-cli@1.8.4

jobs:
  build_gcpcli:
    working_directory: ~/project
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - run:
          name: Initialize gcloud CLI to connect to Google Cloud
          command: |
            # Initialize gcloud CLI
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
      - run:
          name: Gcloud version check and install components.
          command: |
            #check gcloud version
            gcloud version
            #install
            apt-get install -y google-cloud-sdk-app-engine-python
            apt-get install -y python3-venv
      - checkout
      - run:
          name: install local test environment.
          command: |
            cd circleci/google_app_engine
            python3 -m venv env
            source env/bin/activate
            pip install -r requirements.txt
            pwd
            ls -ltr
            python main.py &
      - run:
          name: test_check_webpage
          command: |
            export GET_URL="https://localhost:8080"
            curl -o result_local.html $GET_URL
            cat result_local.html

  deploy_gcpcli:
    working_directory: ~/project
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - run:
          name: Gcloud version
          command: |
            #check gcloud version
            gcloud version
      - run:
          name: deploy google app engine.
          command: |
            gcloud --quiet app deploy ./circleci/google_app_engine/app.yaml

  deploy_aftertest_gcpcli:
    working_directory: ~/project
    docker:
      - image: circleci/python
    steps:
      - run:
          command: |
            export GET_URL="https://$GOOGLE_PROJECT_ID.appspot.com"
            curl -o result.html $GET_URL
            cat result.html
          name: check_webpage
      
workflows:
  version: 2.1
  install_and_check:
    jobs:
      - build_gcpcli
      - deploy_gcpcli:
          requires:
            - build_gcpcli
          filters:
            branches:
              only: master
      - deploy_aftertest_gcpcli:
          requires:
            - deploy_gcpcli
          filters:
            branches:
              only: master
