version: 2.1

#名前空間にgcpをインポート
orbs:
  gcp-cli: circleci/gcp-cli@1.8.4

jobs:
  build_gcpcli:
    working_directory: ~/project
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - run:
          command: |
            # Initialize gcloud CLI
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
          name: Initialize gcloud CLI to connect to Google Cloud

  test_gcpcli_ver:
    working_directory: ~/project
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - run:
          command: |
            #check gcloud version
            gcloud version
          name: Gcloud version
      - run:
          name: check directory.
          command: |
            ls -ltr ./circleci/google_app_engine

  deploy_gcpcli:
      working_directory: ~/project
      docker:
        - image: google/cloud-sdk:latest
      steps:
        - checkout
        - run:
            command: |
              gcloud --quiet app deploy ./circleci/google_app_engine/app.yaml
            name: deploy google app engine.

      
workflows:
  version: 2.1
  install_and_check:
    jobs:
      - build_gcpcli
      - test_gcpcli_ver:
          requires:
            - build_gcpcli
          filters:
            branches:
              only: master
      - deploy_gcpcli:
          requires:
            - build_gcpcli

