version: 2.1

#名前空間にgcpをインポート
orbs:
  gcp-cli: circleci/gcp-cli@1.8.4

workflows:
  install_and_configure_cli:
    jobs:
      #default executor
      - gcp-cli/install_default:
          context: hashiheiContext
          executor: gcp-cli/default
          steps:
            - gcp-cli/install
      #google cloud image
      - gcp-cli/install_gcp:
        steps:
          context: hashiheiContext
          executor: gcp-cli/google
          steps:
            - gcp-cli/install
jobs:
  build:
    docker:
      - image: google/cloud-sdk:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: check time.
          command:  'date'
      - run:
          name: check directory.
          command: |
            ls -ltr
            tree
