version: 2.1
executors:
  build-deploy-executor:
    working_directory: ~/project
    docker:
      - image: google/cloud-sdk:latest


#名前空間にgcpをインポート
orbs:
  gcp-cli: circleci/gcp-cli@1.8.4
  browser-tools: circleci/browser-tools@0.1.4

jobs:
  build_gcpcli:
    executor: build-deploy-executor
    steps:
      - run:
          name: install python3 venv.
          command: |
            #install
            apt-get install -y python3-venv
      - run:
          name: install python lib.
          command: |
            cd circleci/google_app_engine
            python3 -m venv env
            source env/bin/activate
            pip install -r requirements.txt
      - checkout
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum dev.txt" }}
          paths:
            - "venv"
      - run:
          name: test.
          command: |
            cd circleci/google_app_engine
            . venv/bin/activate
            pytest test_main.py > pytestlog.txt
            mkdir /tmp/dumps
            cp -p pytestlog.txt /tmp/dumps
      - store_artifacts:
          path: /tmp/dumps
          destination: tr1
      - store_test_results:
          path: /tmp/dumps

  deploy_all_gcpcli:
    executor: build-deploy-executor
    steps:
      - run:
          name: Initialize gcloud CLI to connect to Google Cloud
          command: |
            # Initialize gcloud CLI
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
      - run:
          name: Gcloud version check and install components.
          command: |
            #check gcloud version
            gcloud version
            #install
            apt-get install -y google-cloud-sdk-app-engine-python
      - run:
          name: deploy google app engine.
          command: |
            gcloud --quiet app deploy ./circleci/google_app_engine/app.yaml --version=test
      - run:
          name: test:check_webpage
          command: |
            export GET_URL="https://$GOOGLE_PROJECT_ID.appspot.com"
            curl -o result.html $GET_URL
            cat result_deploy_all.html
            mkdir /tmp/dumps
            cp -p result_deploy_all.html /tmp/dumps
      - store_artifacts:
          path: /tmp/dumps
      
workflows:
  version: 2.1
  install_and_check:
    jobs:
      - build_gcpcli
      - deploy_all_gcpcli:
          requires:
            - build_gcpcli
