version: 2.1
executors:
  build-deploy-executor:
    working_directory: ~/project
    docker:
      - image: google/cloud-sdk:latest


#名前空間にgcpをインポート
orbs:
  gcp-cli: circleci/gcp-cli@1.8.4
  browser-tools: circleci/browser-tools@0.1.4

jobs:
  build_gcpcli:
    executor: build-deploy-executor
    steps:
      - checkout
      - run:
          name: install python3 venv.
          command: |
            #install
            apt-get install -y python3-venv
      - restore_cache:
          key: deps2-{{ .Branch }}-{{ checksum "circleci/google_app_engine/.circleci/dev.txt" }}
      - run:
          name: install python lib.
          command: |
            python3 -m venv ~/project/circleci/google_app_engine/env
            source ~/project/circleci/google_app_engine/env/bin/activate
            pip install -r ~/project/circleci/google_app_engine/requirements.txt
      - save_cache:
          key: deps2-{{ .Branch }}-{{ checksum "circleci/google_app_engine/.circleci/dev.txt" }}
          paths:
            - 'env'
            
      - run:
          name: make directory
          command: |
            mkdir -pv test-reports
      
      - run:
          name: service up main.py
          command: |
            source ~/project/circleci/google_app_engine/env/bin/activate
            python3 ~/project/circleci/google_app_engine/main.py > test-reports/pylog
          background: true

      - run:
          name: pytest.
          command: |
            source ~/project/circleci/google_app_engine/env/bin/activate
            pytest -rapP --durations=10  --junitxml=test-reports/junit.xml ~/project/circleci/google_app_engine/test_main.py
      - store_artifacts:
          path: test-reports
      - store_test_results:
          path: test-reports
      - add_ssh_keys:
          fingerprints:
            - '3e:ac:02:a3:62:26:ca:78:af:67:f7:9c:f0:68:43:22'

  deploy_all_gcpcli:
    executor: build-deploy-executor
    steps:
      - checkout
      - run:
          name: Initialize gcloud CLI to connect to Google Cloud
          command: |
            # Initialize gcloud CLI
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
      - run:
          name: Gcloud version check and install components.
          command: |
            #check gcloud version
            gcloud version
            #install
            apt-get install -y google-cloud-sdk-app-engine-python
      
      - run:
          name: test gcp local.
          command: |
            ls
          background: true

      - run:
          name: deploy google app engine.
          command: |
            gcloud --quiet app deploy ./circleci/google_app_engine/app.yaml --version=test
      - run:
          name: test:check_webpage
          command: |
            export GET_URL="https://$GOOGLE_PROJECT_ID.appspot.com"
            curl -o result.html $GET_URL
            cat result.html
            mkdir /tmp/dumps
            cp -p result.html /tmp/dumps
      - store_artifacts:
          path: /tmp/dumps
      
workflows:
  version: 2.1
  install_and_check:
    jobs:
      - build_gcpcli
      - deploy_all_gcpcli:
          requires:
            - build_gcpcli
          filters:
            branches:
              only:
                - master
