version: 2.1

#名前空間にgcpをインポート
orbs:
  gcp-cli: circleci/gcp-cli@1.8.4

jobs:
  build_gcpcli:
    working_directory: ~/project
    docker:
      - image: google/cloud-sdk:latest
#    context: hashiheiContext
    steps:
      - checkout
      - run:
          command: |
            # Initialize gcloud CLI
            echo {$GCLOUD_SERVICE_KEY}
            echo {$GOOGLE_PROJECT_ID}
            echo {$GOOGLE_COMPUTE_ZONE}
            gcloud auth activate-service-account --key-file={$GCLOUD_SERVICE_KEY}
            gcloud --quiet config set project {$GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone {$GOOGLE_COMPUTE_ZONE}
          name: Initialize gcloud CLI to connect to Google Cloud

  test_gcpcli_ver:
    working_directory: ~/project
    docker:
      - image: google/cloud-sdk:latest
#    context: hashiheiContext
    steps:
      - checkout
      - run:
          command: |
            #check gcloud version
            gcloud verson
          name: Gcloud version
      - run:
          name: check time.
          command: |
            date
      - run:
          name: check directory.
          command: |
            ls -ltr
            tree
      
workflows:
  version: 2.1
  install_and_check:
    jobs:
      - build_gcpcli
      - test_gcpcli_ver:
          requires:
            - build_gcpcli
          filters:
            branches:
              only: master

